
export const PATHS = {
  HOME: "/",
  LOGIN: "/login",
  REGISTER: "/register",
  UNAUTHORIZED: "/unauthorized",
  NOT_FOUND: "/404",
  CHANGE_PASSWORD: "/change-password",
  FORGOT_PASSWORD: "/forgot-password",
  RESET_PASSWORD: "/reset-password",
  DASHBOARD: "/dashboard",

  ADMIN: {
    DASHBOARD: "/admin/dashboard",
    CLIENTS: "/admin/clients",
    CLIENTS_NEW: "/admin/clients/new",
    CLIENT_DETAILS: (id?: string) => id ? `/admin/clients/${id}` : "/admin/clients/:id",
    PARTNERS: "/admin/partners",
    PARTNER_DETAILS: (id?: string) => id ? `/admin/partners/${id}` : "/admin/partners/:id",
    PARTNER_CLIENTS: (id?: string) => id ? `/admin/partners/${id}/clients` : "/admin/partners/:id/clients",
    PARTNERS_NEW: "/admin/partners/new",
    PAYMENTS: "/admin/payments",
    PAYMENT_DETAILS: (id?: string) => id ? `/admin/payments/${id}` : "/admin/payments/:id",
    PAYMENT_NEW: "/admin/payments/new",
    SALES: "/admin/sales",
    SALES_DETAILS: (id?: string) => id ? `/admin/sales/${id}` : "/admin/sales/:id",
    SALES_NEW: "/admin/sales/new",
    MACHINES: "/admin/machines",
    FEES: "/admin/fees",
    REPORTS: "/admin/reports",
    SETTINGS: "/admin/settings",
    NOTIFICATIONS: "/admin/notifications",
    SUPPORT: "/admin/support",
    SECURITY: "/admin/security",
    COMPANY: "/admin/company",
    COMPANY_REPORTS: "/admin/company/reports",
    COMPANY_EXPENSES: "/admin/company/expenses",
  },

  CLIENT: {
    DASHBOARD: "/client/dashboard",
    PAYMENTS: "/client/payments",
    SUPPORT: "/client/support",
    MACHINES: "/client/machines",
    PROFILE: "/client/profile",
    REPORTS: "/client/reports",
    SETTINGS: "/client/settings",
    HELP: "/client/help",
  },

  PARTNER: {
    DASHBOARD: "/partner/dashboard",
    CLIENTS: "/partner/clients",
    COMMISSIONS: "/partner/commissions",
    SALES: "/partner/sales",
    REPORTS: "/partner/reports",
    SUPPORT: "/partner/support",
    HELP: "/partner/help",
    SETTINGS: "/partner/settings",
  },

  FINANCIAL: {
    DASHBOARD: "/financial/dashboard",
    PAYMENTS: "/financial/payments",
    REPORTS: "/financial/reports",
    SETTINGS: "/financial/settings",
    CLIENTS: "/financial/clients",
    REQUESTS: "/financial/requests",
  },

  LOGISTICS: {
    DASHBOARD: "/logistics/dashboard",
    MACHINES: "/logistics/machines",
    REQUESTS: "/logistics/requests",
    OPERATIONS: "/logistics/operations",
    REPORTS: "/logistics/reports",
    CLIENTS: "/logistics/clients",
    SETTINGS: "/logistics/settings",
    MACHINE_DETAILS: (id?: string) => id ? `/logistics/machines/${id}` : "/logistics/machines/:id",
    NEW_MACHINE: "/logistics/machines/new",
    INVENTORY: "/logistics/inventory",
    SUPPORT: "/logistics/support",
  }
} as const;
