
export enum ClientStatus {
  ACTIVE = "ACTIVE",
  INACTIVE = "INACTIVE",
  PENDING = "PENDING",
  BLOCKED = "BLOCKED"
}

export enum NotificationType {
  PAYMENT = "PAYMENT",
  BALANCE = "BALANCE",
  BALANCE_UPDATE = "BALANCE_UPDATE",
  MACHINE = "MACHINE",
  COMMISSION = "COMMISSION",
  SUPPORT = "SUPPORT",
  SYSTEM = "SYSTEM",
  GENERAL = "GENERAL",
  PAYMENT_APPROVED = "PAYMENT_APPROVED",
  PAYMENT_REJECTED = "PAYMENT_REJECTED",
  PAYMENT_REQUEST = "PAYMENT_REQUEST",
  SALE = "SALE"
}

export enum PaymentStatus {
  PENDING = "PENDING",
  APPROVED = "APPROVED",
  REJECTED = "REJECTED",
  PAID = "PAID",
  PROCESSING = "PROCESSING"
}

export enum PaymentType {
  PIX = "PIX",
  TED = "TED",
  BOLETO = "BOLETO",
  CREDIT = "CREDIT",
}

export enum UserRole {
  ADMIN = "ADMIN",
  CLIENT = "CLIENT",
  FINANCIAL = "FINANCIAL",
  PARTNER = "PARTNER", 
  LOGISTICS = "LOGISTICS",
  USER = "USER",
  MANAGER = "MANAGER",
  FINANCE = "FINANCE",
  SUPPORT = "SUPPORT"
}

export enum PaymentAction {
  APPROVE = "APPROVE",
  REJECT = "REJECT",
  VIEW = "VIEW",
  DELETE = "DELETE",
  SEND_RECEIPT = "SEND_RECEIPT"
}
