
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjzwusatnkebfpsvvffz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqend1c2F0bmtlYmZwc3Z2ZmZ6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU4NTQzMDUsImV4cCI6MjA2MTQzMDMwNX0.7h8KmMLCB7OTSrj0OCisx1DJ_p9MqcI9G1bZFzfIc0I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: true,
    autoRefreshToken: true,
    storage: typeof window !== 'undefined' ? sessionStorage : undefined,
    detectSessionInUrl: true,
    flowType: 'implicit'
  }
});

